/////////AUTH
export const LOGIN = 'LOGIN';
export const LOADING = 'LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const LOGIN_FAIL = 'LOGIN_FAIL';

/////////PERFILES
export const GET_PREFERENCIAS = 'GET_PREFERENCIAS';
export const CARGAR_PREFERENCIAS = 'CARGAR_PREFERENCIAS';
export const AGREGAR_PREFERENCIA = 'AGREGAR_PREFERENCIA';
export const ELIMINAR_PREFERENCIA = 'ELIMINAR_PREFERENCIA';
export const AGREGA_CATEGORIA = 'AGREGA_CATEGORIA';

////////Dashboard
export const GET_NOTICIAS = 'GET_NOTICIAS';
export const LOADING_NOTICIAS = 'LOADING_NOTICIAS';
export const GET_ARTICULOS = 'GET_ARTICULOS';
export const LOADING_ARTICULOS = 'LOADING_ARTICULOS';
export const RESET_ARTICULOS = 'RESET_ARTICULOS';
export const GET_VIDEOS = 'GET_VIDEOS';
export const LOADING_VIDEOS = 'LOADING_VIDEOS';
export const GET_MEGUSTA = 'GET_MEGUSTA';
export const AGREGA_MEGUSTA = 'AGREGA_MEGUSTA';
export const ELIMINA_MEGUSTA = 'ELIMINA_MEGUSTA';
export const ELIMINA_CATEGORIA = 'ELIMINA_CATEGORIA';


